### ISSUE TITLE
Update setup.py installation 

### ISSUE THREAD

**Issue by bisejdiu** [ProLint/ufcc#17]
`ufcc` installation using setup.py does not work, at least not on MacOS. 

Can you have a look at that and confirm that it is working on Linux?

**Comment by danielpastor97** [comment]
Done! It was installing without trouble but because I was doing it in an environment with a lot of packages already installed. When I created a new empty environment the installation from the setup.py file did crash, but I already fixed it and opened a pull request to merge the changes to the `main` branch.
